version: '2'
services:
  db:
    image: mongo:latest
    container_name: mongo_local
    ports:
    - 27017:27017

  app:
    build: src
    env_file:
      - .env
    command: [
      "python",
      "-m",
      "cli",
      "--id",
      "${TWITTER_HANDLE}",
      "--mongo-url",
      "${MONGO_URL}",
      "--db",
      "${MONGO_DB}",
      "twitter"
    ]
    depends_on:
      - db
