twitter: python3 -m cli --id $TWITTER_HANDLE --mongo-url $MONGO_URL --db $MONGO_DB twitter
keybase: python3 -m cli --id $KEYBASE_HANDLE --mongo-url $MONGO_URL --db $MONGO_DB keybase
github: python3 -m cli --id $GITHUB_USERNAME --mongo-url $MONGO_URL --db $MONGO_DB github
stackoverflow: python3 -m cli --id $STACKOVERFLOW_HANDLE --mongo-url $MONGO_URL --db $MONGO_DB stackoverflow
linkedin: docker container run --rm \
    -e SENTRY_DSN=$SENTRY_DSN \
    -e LINKEDIN_USERNAME=$LINKEDIN_USERNAME \
    -e LINKEDIN_PASSWORD=$LINKEDIN_PASSWORD \
    -e LINKEDIN_PROFILE_HANDLE=$LINKEDIN_PROFILE_HANDLE \
    -e MONGO_URL=$MONGO_URL \
    -e MONGO_DB=$MONGO_DB \
    anubhavcodes/socialkarma:latest \
    python3 -m cli --id $LINKEDIN_PROFILE_HANDLE --username $LINKEDIN_USERNAME --password $LINKEDIN_PASSWORD --mongo-url $MONGO_URL --db $MONGO_DB linkedin
